# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
name: Build provider
description: Build the enos-provider
inputs:
  target:
    description: The platform and operation system to build, i.e linux/amd64.
    required: true
    default: linux/amd64
outputs:
  arch:
    description: The target artifact os
    value: ${{ steps.meta.outputs.arch }}
  name:
    description: The target artifact name
    value: ${{ steps.gen-output.outputs.targets }}
  os:
    description: The target artifact os
    value: ${{ steps.meta.outputs.os }}

runs:
  using: composite
  steps:
    - uses: ./.github/actions/build-flight-control
    - id: meta
      shell: bash
      run: |
        {
          os=$(cut -d "/" -f1 "${{ inputs.target }}")
          arch=$(cut -d "/" -f2 "${{ inputs.target }}")
          echo "os=$os"
          echo "arch=$arch"
        } | tee -a "$GITHUB_OUTPUT"
    - name: Build enos-provider ${{ inputs.target }}
      env:
        PROVIDER_BIN_OS: ${{ steps.split.outputs.os }}
        PROVIDER_BIN_ARCH: ${{ steps.split.outputs.arch }}
      run: make build
      shell: bash
    - id: gen-output
      shell: bash
      run: |
        {
          echo "artifact=$(ls dist)"
        } | tee -a "$GITHUB_OUTPUT"
