# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ci-test.fullname" . }}
  labels:
    {{- include "ci-test.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ci-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ci-test.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{/* Just spin forever tailing /dev/null */}}
          command: ["tail", "-f", "/dev/null"]
