---
name: promote enos-provider to hashicorp-qti/enos

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from enosdev to enos private provider registry
# in hashicorp-qti org in TFC
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from enosdev TFC private registry'
        required: true

jobs:
  test-enosdev:
    name: test enos-provider from hashicorp-qti/enosdev
    uses: ./.github/workflows/test_enosdev.yml
    with:
      enos_provider_version: ${{ github.event.inputs.version }}
    secrets: inherit

  promote-enosdev:
    name: promote enos-provider to hashicorp-qti/enos
    runs-on: ubuntu-latest
    needs: test-enosdev
    env:
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: import gpg key
        # switching to upstream action as suggested in https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIV_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: promote enos-provider to hashicorp-qti/enos
        run: |
          gpg --list-signatures
          go run ./tools/publish/cmd tfc promote --provider-version $ENOS_VERSION --token $TFC_PUBLISH_TOKEN
        env:
          TFC_PUBLISH_TOKEN: ${{ secrets.TFC_PUBLISH_TOKEN }}
          ENOS_VERSION: ${{ github.event.inputs.version }}

  test-enos:
    name: test enos-provider from hashicorp-qti/enos
    needs: promote-enosdev
    uses: ./.github/workflows/test_enos.yml
    secrets: inherit
