---
name: promote to hashicorp-qti/enos

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from enosdev to enos private provider registry
# in hashicorp-qti org in TFC
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from enosdev TFC private registry'
        required: true

jobs:
  test-enosdev:
    uses: ./.github/workflows/test_enosdev.yml
    with:
      enos_provider_version: ${{ github.event.inputs.version }}
    secrets: inherit

  promote-enosdev:
    name: promote enos-provider to hashicorp-qti/enos
    runs-on: ubuntu-latest
    needs: test-enosdev
    env:
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: go.mod
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41 # v5.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIV_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Promote enos-provider to hashicorp-qti/enos
        run: |
          gpg --list-signatures
          go run ./tools/publish/cmd tfc promote --provider-version $ENOS_VERSION --token $TFC_PUBLISH_TOKEN
        env:
          TFC_PUBLISH_TOKEN: ${{ secrets.TFC_PUBLISH_TOKEN }}
          ENOS_VERSION: ${{ github.event.inputs.version }}

  test-enos:
    needs: promote-enosdev
    uses: ./.github/workflows/test_enos.yml
    secrets: inherit
