---
name: Promote Enos Provider in TFC

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from enosdev to enos private provider registry
# in hashicorp-qti org in TFC
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from enosdev TFC private registry'
        required: true

jobs:
  call-test-tfcrelease:
    name: "Install and test enosdev provider"
    uses: ./.github/workflows/test_tfcrelease.yml
    with:
      enos_provider_name: "enosdev"
      enos_provider_version: ${{ github.event.inputs.version }}
    # Use the inherit keyword to pass all the calling workflow's secrets to the called workflow.
    # This includes all secrets the calling workflow has access to, namely organization,
    # repository, and environment secrets.
    secrets: inherit

  promote-tfcartifact:
    name: "Promote Enos provider TFC Artifact"
    runs-on: ubuntu-latest
    needs: call-test-tfcrelease
    env:
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Import GPG key
        id: import_gpg
        # switching to upstream action as suggested in https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIV_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Promote Enos provider artifact from enosdev to enos"
        id: tfcpromote
        run: |
          gpg --list-signatures
          go run ./tools/publish/cmd tfc promote --provider-version $ENOS_VERSION --token $TFC_PUBLISH_TOKEN
        env:
          TFC_PUBLISH_TOKEN: ${{ secrets.TFC_PUBLISH_TOKEN }}
          ENOS_VERSION: ${{ github.event.inputs.version }}

  call-test-promoted-tfcrelease:
    name: "Install and Test promoted TFC Artifact"
    needs: promote-tfcartifact
    uses: ./.github/workflows/test_tfcrelease.yml
    with:
      enos_provider_name: "enos"
      enos_provider_version: ${{ github.event.inputs.version }}
    # Use the inherit keyword to pass all the calling workflow's secrets to the called workflow.
    # This includes all secrets the calling workflow has access to, namely organization,
    # repository, and environment secrets.
    secrets: inherit
