---
name: promote to hashicorp-qti/enos

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from enosdev to enos private provider registry
# in hashicorp-qti org in TFC
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from enosdev TFC private registry'
        required: true

jobs:
  test-enosdev:
    uses: ./.github/workflows/test_enosdev.yml
    with:
      enos_provider_version: ${{ github.event.inputs.version }}
    secrets: inherit

  promote-enosdev:
    name: promote enos-provider to hashicorp-qti/enos
    runs-on: ubuntu-latest
    needs: test-enosdev
    env:
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIV_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Promote enos-provider to hashicorp-qti/enos
        run: |
          gpg --list-signatures
          go run ./tools/publish/cmd tfc promote --provider-version $ENOS_VERSION --token $TFC_PUBLISH_TOKEN
        env:
          TFC_PUBLISH_TOKEN: ${{ secrets.TFC_PUBLISH_TOKEN }}
          ENOS_VERSION: ${{ github.event.inputs.version }}

  test-enos:
    needs: promote-enosdev
    uses: ./.github/workflows/test_enos.yml
    secrets: inherit
