---
name: Promote

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from Current to Stable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from current'
        required: true

jobs:
  test-artifact:
    name: "Install and Test Artifact"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147451547303:role/github_actions-Enos-Provider
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Vault Enterprise License
        id: license
        run: echo "${{ secrets.VAULT_LICENSE }}" > /tmp/vault.hclic
      - name: Setup mirror
        id: mirror
        run: cat ./cd-tests/mirror.hcl >> ${HOME}/.terraformrc
      - name: Setup Enos SSH Keys
        id: sshkey
        run: |
          echo "${{ secrets.ENOS_CI_SSH_KEYPAIR }}" > ./cd-tests/enos-ci-ssh-keypair.pem
          chmod 600 ./cd-tests/enos-ci-ssh-keypair.pem
      - name: "Update Provider Version"
        run: |
          sed "s/ENOS_VER/$ENOS_VERSION/g" main.tf > main.tf.upt
          mv main.tf.upt main.tf
        working-directory: ./cd-tests
      - name: "Terraform Plan Test for Provider"
        # validate example terraform that utilizes the provider.
        run: |
          terraform init -backend-config=backend.hcl
          terraform plan -no-color
        working-directory: ./cd-tests
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        continue-on-error: true
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./cd-tests
      - name: Terraform Apply Retry
        # Retry apply if it times out on Route table association
        id: retry_apply
        if: steps.apply.outcome == 'failure'
        run: |
          terraform plan -no-color
          terraform apply -auto-approve
        working-directory: ./cd-tests
      - name: Terraform Destroy
        id: destroy
        if: ${{ always() }}
        run: terraform destroy -auto-approve
        working-directory: ./cd-tests

  enos-e2e:
    name: "Enos - E2E tests"
    runs-on: ubuntu-latest
    env:
      TFC_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      ENOS_RELEASE_NAME: enosdev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Enos
        uses: hashicorp/action-setup-enos@v1
        with:
          github-token:
            ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: K8S tests
        id: enoscli-k8s
        env:
          ENOS_VAR_tfc_api_token: ${{ secrets.TF_API_TOKEN }}
          TFC_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          ENOS_RELEASE_NAME: enosdev
        run: make test-k8s-dev

  promote:
    name: "Promote Artifact"
    runs-on: ubuntu-latest
    needs: [test-artifact, enos-e2e]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147451547303:role/github_actions-Enos-Provider
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Promote to enos-provider-stable S3 bucket
        run: go run ./tools/publish/cmd s3 copy --version $ENOS_VERSION --src-bucket enos-provider-current --dest-bucket enos-provider-stable
