---
name: Promote

# This workflow is run manually from GH Actions to Test and Promote
# the Enos-Provider Artifact from Current to Stable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote from current'
        required: true

# These permissions are necessary for the doormat-action to get the OIDC token
permissions:
  contents: read
  id-token: write

jobs:
  test-artifact:
    name: "Install and Test Artifact"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Assume service user role via Doormat
        uses: hashicorp/doormat-action@main
        with:
          # This role, its associated IAM policy, the allowed Github workflow
          # event types and their associated qualifiers are managed via
          # Terraform in the hashicorp/enos-ci repository. If you wish to allow
          # AWS credentials for different Github event types, workflows or
          # branches you'll need to update the role there.
          aws-role-arn: arn:aws:iam::147451547303:role/enos-provider
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Vault Enterprise License
        id: license
        run: echo "${{ secrets.VAULT_LICENSE }}" > /tmp/vault.hclic
      - name: Setup mirror
        id: mirror
        run: cat ./cd-tests/mirror.hcl >> ${HOME}/.terraformrc
      - name: Setup Enos SSH Keys
        id: sshkey
        run: |
          echo "${{ secrets.ENOS_CI_SSH_KEY }}" > ./cd-tests/enos-ci-ssh-key.pem
          chmod 600 ./cd-tests/enos-ci-ssh-key.pem
      - name: "Update Provider Version"
        run: |
          sed "s/ENOS_VER/$ENOS_VERSION/g" main.tf > main.tf.upt
          mv main.tf.upt main.tf
        working-directory: ./cd-tests
      - name: "Terraform Plan Test for Provider"
        # validate example terraform that utilizes the provider.
        run: |
          terraform init -backend-config=backend.hcl
          terraform plan -no-color
        working-directory: ./cd-tests
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        continue-on-error: true
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./cd-tests
      - name: Terraform Apply Retry
        # Retry apply if it times out on Route table association
        id: retry_apply
        if: steps.apply.outcome == 'failure'
        run: |
          terraform plan -no-color
          terraform apply -auto-approve
        working-directory: ./cd-tests
      - name: Terraform Destroy
        id: destroy
        if: ${{ always() }}
        run: terraform destroy -auto-approve
        working-directory: ./cd-tests

  promote:
    name: "Promote Artifact"
    runs-on: ubuntu-latest
    needs: test-artifact
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENOS_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147451547303:role/github_actions-Enos-Provider
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Promote to enos-provider-stable S3 bucket
        run: go run ./tools/publish/cmd s3 copy --version $ENOS_VERSION --src-bucket enos-provider-current --dest-bucket enos-provider-stable
