---
name: Release

on:
  # Allow the release pipeline to be triggered manually from GH Actions menu
  # This will release the version in `VERSION` file on `main` branch
  workflow_dispatch:
  # Run the release pipeline on merge only when VERSION is updated
  push:
    paths:
      - 'VERSION'
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147451547303:role/github_actions-Enos-Provider
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Build and Install Artifacts
        run: CI='true' make
      - name: Publish to S3 bucket
        run: go run ./tools/publish/cmd s3 upload --dist ./dist --bucket enos-provider-current
#        Fails on GPG signing so temporarily disabled
#      - name: Upload to TFC private registry
#        id: tfcupload
#        run: |
#          sudo apt-get update
#          sudo apt-get install expect
#          export GPG_TTY=$(tty)
#          echo "${{ secrets.GPG_PRIV_SIGNING_KEY }}" | gpg --batch --import
#          echo "${{ secrets.GPG_PUB_SIGNING_KEY }}" | gpg --import
#          expect -c 'spawn gpg --edit-key 5D67D7B072C16294 trust quit; send "5\ry\r"; expect eof'
#          gpg --list-signatures
#          go run ./tools/publish/cmd tfc upload --rename-binary "terraform-provider-enosdev" --provider-name "enosdev" --token "$TFC_TOKEN"
#        env:
#          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
#          GPG_TTY: $(tty)
