---
name: release

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The sha to associated with the release
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ inputs.sha }}   # checkout out our sha to get the version
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - uses: ./.github/actions/build-provider
      - name: Upload artifacts
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: release-artifacts
          path: dist
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  test-build-artifacts:
    needs: build
    name: enos scenario run
    uses: ./.github/workflows/run-sample.yml
    secrets: inherit
    with:
      sample-name: dev
      download: release-artifacts

  release:
    needs:
      - build
      - test-build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ inputs.sha }}   # checkout out our sha to get the version
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
      - uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4.1.5
        with:
          path: dist
          name: release-artifacts
          merge-multiple: true
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create a Github release
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        run: |
          gpg --list-signatures
          # actions/download-artifact doesn't preserve file permissions. Reset the exec bits.
          chmod 755 dist/*
          go run ./tools/publish/cmd github create \
            --dist ./dist \
            --gpg-key-id "${{ secrets.GPG_KEY_ID }}" \
            --commit "${{ inputs.sha }}" \
            --version "$(cat VERSION)" \
            --manifest-path terraform-registry-manifest.json
