---
name: Release

on:
  push:
    branches:
      - main
      # - shain/badgenstuff # testing for main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build code
        run: CI='true' make release
