---
name: release

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The sha to associated with the release
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      linux-amd64-artifact: ${{ steps.outputs.outputs.linux-amd64-artifact }}
    strategy:
      fail-fast: true
      matrix:
        arch:
          - amd64
          - arm64
        os:
          - darwin
          - linux
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.sha }}   # checkout out our sha to get the version
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - id: build
        uses: ./.github/actions/build-provider
        with:
          target: ${{matrix.os}}/${{ matrix.arch }}
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ steps.build.outputs.name }}
          path: dist/${{ steps.build.outputs.name }}
          if-no-files-found: error
          retention-days: 1
      - id: outputs
        run: |
          {
            echo "linux-amd64-artifact=terraform-provider-enos_$(cat VERSION)_linux_amd64"
          } | tee -a "$GITHUB_OUTPUT"

  test-build-artifacts:
    needs: build
    name: enos scenario run
    uses: ./.github/workflows/run-sample.yml
    secrets: inherit
    with:
      sample-name: dev
      download: ${{ needs.build.outputs.linux-amd64-artifact }}

  release:
    needs:
      - build
      - test-build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.sha }}   # checkout out our sha to get the version
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: dist
          pattern: terraform-provider-enos_*
          merge-multiple: true
      - run: |
          ls -al ./dist
          chmod +x ./dist/*
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create a Github release
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        run: |
          gpg --list-signatures
          # actions/download-artifact doesn't preserve file permissions. Reset the exec bits.
          chmod 755 dist/*
          go run ./tools/publish/cmd github create \
            --dist ./dist \
            --gpg-key-id "${{ secrets.GPG_KEY_ID }}" \
            --commit "${{ inputs.sha }}" \
            --version "$(cat VERSION)" \
            --manifest-path terraform-registry-manifest.json
