---
name: run-scenario

on:
  workflow_dispatch:
    inputs:
      scenario-filter:
        description: The filter of the scenario to run
        required: true
        type: string
  workflow_call:
    inputs:
      download:
        type: string
        required: false
      scenario-filter:
        required: true
        type: string

jobs:
  run:
    name: ${{ inputs.scenario-filter }}
    runs-on: ubuntu-latest
    env:
      ENOS_DEBUG_DATA_ROOT_DIR: /tmp/enos/logs
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          # The github actions service user creds for this account managed in hashicorp/enos-ci
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_09042025 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_09042025 }}
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          # the terraform wrapper will break terraform execution in enos because
          # it changes the output to text when we expect it to be JSON.
          terraform_wrapper: false
      - uses: hashicorp/action-setup-enos@6ec106c8f809fe645162d73bea565c65f3269907 # v1.52
        with:
          github-token:
            ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: Set up support files
        run: |
          mkdir -p enos/support
          echo "${{ secrets.ENOS_CI_SSH_KEY }}" > enos/support/enos-ci-ssh-key.pem
          echo "${{ secrets.VAULT_LICENSE }}" > enos/support/vault.hclic
          echo "${{ secrets.CONSUL_LICENSE }}" > enos/support/consul.hclic
          chmod 600 enos/support/enos-ci-ssh-key.pem
          chmod 600 enos/support/vault.hclic
          chmod 600 enos/support/consul.hclic
      - if: github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/build-provider
        with:
          target: linux/amd64
      - if: github.event_name != 'workflow_dispatch'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          name: ${{ inputs.download }}
      - run: chmod +x ./dist/*
      - run: enos scenario run ${{ inputs.scenario-filter }}
        working-directory: enos
      - if: ${{ always() }}
        run: enos scenario destroy ${{ inputs.scenario-filter }}
        working-directory: enos
      - name: Remove enos runtime directories
        if: ${{ always() }}
        run: |
          rm -rf /tmp/enos*
          rm -rf enos/support
          rm -rf enos/.enos
          rm -rf "$HOME/.terraform.d"
