---
name: run-scenario-vault-ssh

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
      backend:
        required: true
        type: string
      consul_edition:
        required: false
        type: string
        default: oss
      consul_version:
        required: false
        type: string
        default: 1.15.3
      distro:
        required: true
        type: string
      edition:
        required: true
        type: string
      enos_provider_version:
        type: string
      use:
        required: true
        type: string
      unseal_method:
        required: true
        type: string
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      backend:
        required: true
        type: string
      consul_edition:
        required: false
        type: string
        default: oss
      consul_version:
        required: false
        type: string
        default: 1.15.3
      distro:
        required: true
        type: string
      edition:
        required: true
        type: string
      enos_provider_version:
        type: string
      use:
        required: true
        type: string
      unseal_method:
        required: true
        type: string
      version:
        required: true
        type: string

# These permissions are necessary for the doormat-action to get the OIDC token
permissions:
  contents: read
  id-token: write

jobs:
  scenario-vault:
    name: "enos scenario run vault arch:${{ inputs.arch }} backend:${{ inputs.backend }} consul_edition:${{ inputs.consul_edition }} consul_version:${{ inputs.consul_version }} distro:${{ inputs.distro }} edition:${{ inputs.edition }} use:${{ inputs.use }} unseal_method:${{ inputs.unseal_method }} version:${{ inputs.version }}"
    runs-on: ubuntu-latest
    env:
      ENOS_DEBUG_DATA_ROOT_DIR: /tmp/enos/logs
      ENOS_VAR_enosdev_provider_version: ${{ inputs.enos_provider_version }}
      ENOS_VAR_tfc_api_token: ${{ secrets.TF_API_TOKEN }}
      ENOS_VAR_consul_release: '{edition = "${{ inputs.consul_edition }}", version = "${{ inputs.consul_version }}"}'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
      - uses: hashicorp/doormat-action@main
        with:
          # This role, its associated IAM policy, the allowed Github workflow
          # event types and their associated qualifiers are managed via
          # Terraform in the hashicorp/enos-ci repository. If you wish to allow
          # AWS credentials for different Github event types, workflows or
          # branches you'll need to update the role there.
          aws-role-arn: arn:aws:iam::147451547303:role/enos-provider
      - uses: hashicorp/setup-terraform@v2
        with:
          # the terraform wrapper will break terraform execution in enos because
          # it changes the output to text when we expect it to be JSON.
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: hashicorp/action-setup-enos@v1
        with:
          github-token:
            ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: Set up support files
        run: |
          mkdir -p enos/support
          echo "${{ secrets.ENOS_CI_SSH_KEY }}" > enos/support/enos-ci-ssh-key.pem
          echo "${{ secrets.VAULT_LICENSE }}" > enos/support/vault.hclic
          echo "${{ secrets.CONSUL_LICENSE }}" > enos/support/consul.hclic
          chmod 600 enos/support/enos-ci-ssh-key.pem
          chmod 600 enos/support/vault.hclic
          chmod 600 enos/support/consul.hclic
      - if: ${{ inputs.use == 'dev' }}
        uses: ./.github/actions/build-provider
        with:
          target: linux/amd64
      - run: enos scenario run vault arch:${{ inputs.arch }} backend:${{ inputs.backend}} distro:${{ inputs.distro }} edition:${{ inputs.edition }} unseal_method:${{ inputs.unseal_method }} use:${{ inputs.use }} version:${{ inputs.version }} --timeout 60m0s
        working-directory: enos
      - if: ${{ always() }}
        run: enos scenario destroy vault arch:${{ inputs.arch }} backend:${{ inputs.backend}} distro:${{ inputs.distro }} edition:${{ inputs.edition }} unseal_method:${{ inputs.unseal_method }} use:${{ inputs.use }} version:${{ inputs.version }} --timeout 60m0s
        working-directory: enos
      - name: Remove enos runtime directories
        if: ${{ always() }}
        run: |
          rm -rf /tmp/enos*
          rm -rf enos/support
          rm -rf enos/.enos
          rm -rf $HOME/.terraform.d
