---
name: Test Current Release

on:
  # Allow this pipeline to be triggered manually from GH Actions menu
  workflow_dispatch:
  # This workflow runs only when Enos-Provider is successfully
  # released to Current bucket
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  test-current-release:
    name: "Install and Test Current Artifact"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147451547303:role/github_actions-Enos-Provider
          role-skip-session-tagging: true
          role-duration-seconds: 3600
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Vault Enterprise License
        id: license
        run: echo "${{ secrets.VAULT_LICENSE }}" > /tmp/vault.hclic
      - name: Setup mirror
        id: mirror
        run: cat ./cd-tests/mirror.hcl >> ${HOME}/.terraformrc
      - name: Setup Enos SSH Keys
        id: sshkey
        run: |
          echo "${{ secrets.ENOS_CI_SSH_KEYPAIR }}" > ./cd-tests/enos-ci-ssh-keypair.pem
          chmod 600 ./cd-tests/enos-ci-ssh-keypair.pem
      - name: "Update Provider Version"
        run: |
          export ENOS_VERSION=$(cat ../VERSION)
          sed "s/ENOS_VER/$ENOS_VERSION/g" main.tf > main.tf.upt
          mv main.tf.upt main.tf
        working-directory: ./cd-tests
      - name: "Terraform Plan Test for Provider"
        # validate example terraform that utilizes the provider.
        run: |
          terraform init -backend-config=backend.hcl
          terraform plan -no-color
        working-directory: ./cd-tests
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./cd-tests
      - name: Terraform Apply Status
        if: steps.apply.outcome == 'failure'
        run: exit 1
      - name: Terraform Destroy
        id: destroy
        if: ${{ always() }}
        run: terraform destroy -auto-approve
        working-directory: ./cd-tests

# TODO: Enable Slack notification for failed workflow
