---
name: upload to hashicorp-qti/enosdev

on:
  # Allow the release pipeline to be triggered manually from GH Actions menu
  # This will release the version in `VERSION` file on `main` branch
  workflow_dispatch:
  # Run the release pipeline on merge only when VERSION is updated
  push:
    paths:
      - 'VERSION'
    branches:
      - main

# These permissions are necessary for the doormat-action to get the OIDC token
permissions:
  contents: read
  id-token: write

jobs:
  upload-enosdev:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo so we can checkout the correct branch
      - name: Determine enos-provider version
        id: get-version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
      - uses: hashicorp/doormat-action@main
        with:
          # This role, its associated IAM policy, the allowed Github workflow
          # event types and their associated qualifiers are managed via
          # Terraform in the hashicorp/enos-ci repository. If you wish to allow
          # AWS credentials for different Github event types, workflows or
          # branches you'll need to update the role there.
          aws-role-arn: arn:aws:iam::147451547303:role/enos-provider
      - uses: ./.github/actions/build-provider
      - name: Import gpg key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIV_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Upload enos-provider to hashicorp-qti/enosdev
        run: |
          gpg --list-signatures
          go run ./tools/publish/cmd tfc upload --rename-binary "terraform-provider-enosdev" --provider-name "enosdev" --token "$TFC_PUBLISH_TOKEN"
        env:
          TFC_PUBLISH_TOKEN: ${{ secrets.TFC_PUBLISH_TOKEN }}

  test-enosdev:
    needs: upload-enosdev
    uses: ./.github/workflows/test_enosdev.yml
    secrets: inherit
    with:
      enos_provider_version: ${{ needs.upload-enosdev.outputs.version }}
