---
name: Validate

on:
  push:

jobs:
  build-and-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build code
        # build the provider, install as terraform plugin, and validate example
        # terraform that utilizes the provider.
        run: make test-tf  # runs build + install make targets
        # TODO:
        # - name: Upload artifacts to actions workflow
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: ${{ github.event.repository.name }}-artifacts
        #     path: |
        #       ./bin/

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build assets
        run: 'sudo apt-get install -y upx-ucl && make flight-control-build'
      - name: Test code
        run: make test

  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build assets
        run: 'sudo apt-get install -y upx-ucl && make flight-control-build'
      - name: Acceptance Tests
        run: make test-acc

  go-lint:
    runs-on: ubuntu-latest
    container: docker.mirror.hashicorp.services/golangci/golangci-lint:latest-alpine
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build assets
        run: 'apk add upx make && make flight-control-build'
      - name: Go Lint
        run: golangci-lint run --out-format=github-actions --timeout=5m0s

# TODO:
# Add security scan
