---
name: Validate

on:
  pull_request:

# These permissions are necessary for the doormat-action to get the OIDC token
permissions:
  contents: read
  id-token: write

jobs:
  go-lint:
    name: "Go lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run -v -c .golangci.yml --out-format=github-actions --timeout=5m0s

  enos-fmt:
    name: "Enos Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume service user role via Doormat
        uses: hashicorp/doormat-action@main
        with:
          # This role, its associated IAM policy, the allowed Github workflow
          # event types and their associated qualifiers are managed via
          # Terraform in the hashicorp/enos-ci repository. If you wish to allow
          # AWS credentials for different Github event types, workflows or
          # branches you'll need to update the role there.
          aws-role-arn: arn:aws:iam::147451547303:role/enos-provider
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # the terraform wrapper will break terraform execution in enos because
          # it changes the output to text when we expect it to be JSON.
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Setup Enos
        uses: hashicorp/action-setup-enos@v1
        with:
          github-token:
            ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: Validate Enos Format
        run: enos fmt -cd
        working-directory: ./enoscli-tests

  unit:
    name: "Unit Tests and Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build assets
        run: 'sudo apt-get install -y upx-ucl && make flight-control-build'
      - name: Test code
        run: make test
      - name: Check formatting
        run: |
          go install mvdan.cc/gofumpt@latest
          make fmt

  build-and-terraform:
    name: "Build and Test Terraform"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: "Build code & Test core example"
        # build the provider, install as terraform plugin, and validate example
        # terraform that utilizes the provider.
        run: make test-tf  # runs build + install make targets
        # TODO:
        # - name: Upload artifacts to actions workflow
        #   uses: actions/upload-artifact@v2
        #   with:
        #     name: ${{ github.event.repository.name }}-artifacts
        #     path: |
        #       ./bin/
      - name: "Terraform Test Artifactory Example"
        # validate example terraform that utilizes the provider.
        run: |
          terraform -chdir=examples/artifactory init
          terraform -chdir=examples/artifactory fmt -check -recursive
          terraform -chdir=examples/artifactory validate

  acceptance:
    name: "Acceptance Tests"
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume service user role via Doormat
        uses: hashicorp/doormat-action@main
        with:
          # This role, its associated IAM policy, the allowed Github workflow
          # event types and their associated qualifiers are managed via
          # Terraform in the hashicorp/enos-ci repository. If you wish to allow
          # AWS credentials for different Github event types, workflows or
          # branches you'll need to update the role there.
          aws-role-arn: arn:aws:iam::147451547303:role/enos-provider
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: ./ci-tests
      - name: Setup Remote Host
        id: setup-remote-host
        working-directory: ./ci-tests
        run: |
          terraform init
          terraform plan -no-color
          terraform apply -auto-approve
          HOST_IP=$(terraform output instance_public_ip | tr -d \" | tr -d "\n")
          echo "host_ip=$HOST_IP" >> $GITHUB_ENV
      - name: Setup Enos SSH Keys
        id: sshkey
        run: |
          echo "${{ secrets.ENOS_CI_SSH_KEY }}" > ./internal/plugin/enos-ci-ssh-key.pem
          echo "${{ secrets.ENOS_CI_SSH_KEY }}" > ./internal/transport/ssh/enos-ci-ssh-key.pem
          chmod 600 ./internal/plugin/enos-ci-ssh-key.pem
          chmod 600 ./internal/transport/ssh/enos-ci-ssh-key.pem
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build assets
        run: 'sudo apt-get install -y upx-ucl && make flight-control-build'
      - name: Acceptance Tests
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_PRODUCT_VERSION: "1.7.0"
          ARTIFACTORY_REVISION: "f45845666b4e552bfc8ca775834a3ef6fc097fe0"
          ENOS_TRANSPORT_USER: "ubuntu"
          ENOS_TRANSPORT_PRIVATE_KEY_PATH: "./enos-ci-ssh-key.pem"
          ENOS_TRANSPORT_HOST: ${{ env.host_ip }}
        run: make test-acc
      - name: Terraform Destroy
        if: always()
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./ci-tests

# TODO:
# Add security scan
