---
name: Build flight-control
description: Build flight-control

runs:
  using: composite
  steps:
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version-file: .go-version
    - name: Install upx
      run: |
        curl -Lo upx.tar.xz https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz
        tar -xvf upx.tar.xz
        sudo mv upx*/upx /usr/local/sbin/
      shell: bash
    - name: Build flight-control
      run: make flight-control
      shell: bash
