# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
name: Build flight-control
description: Build flight-control

runs:
  using: composite
  steps:
    - name: Install upx
      run: |
        curl -Lo upx.tar.xz https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
        tar -xvf upx.tar.xz
        sudo mv upx*/upx /usr/local/sbin/
      shell: bash
    - name: Build flight-control
      run: make flight-control
      shell: bash
